import { IFilm } from '../../../interfaces/IFilm';

/**
 * AUTO-GENERATED by tools/scrape-cinema.mjs — do not edit by hand.
 * Source: https://www.thessalonikiguide.gr/cinema/
 * Generated: 2026-06-06T14:18:51.479Z
 *
 * Re-run `npm run scrape:cinema` to refresh the listings and showtimes.
 */
export const SCRAPED_AT = '';

export const FILMS: IFilm[] = [
];
