import { IFilm } from '../../../interfaces/IFilm';

/**
 * AUTO-GENERATED by tools/scrape-cinema.mjs — do not edit by hand.
 * Source: https://www.thessalonikiguide.gr/cinema/
 * Generated: 2026-06-06T14:18:51.479Z
 *
 * Re-run `npm run scrape:cinema` to refresh the listings and showtimes.
 */
export const SCRAPED_AT = '2026-06-06T14:18:51.479Z';

export const FILMS: IFilm[] = [
  {
    slug: 'arkoydotrypa-2025',
    title: 'Αρκουδότρυπα',
    year: 2025,
    durationMin: 127,
    genres: [
      'Ελληνική Ταινία',
      'Μυστηρίου',
      'Περιπέτεια',
      'Ρομαντική',
    ],
    director: 'Στέργιος Ντινόπουλος,',
    cast: [
      'Χαρά Κυριαζή',
      'Πάμελα Οικονομάκη',
      'Σοφία Λινοσπόρη',
      'Βάσω Γκουγκάρα',
      'Λευτέρης Τσάτσης',
      'Σώζος Χρήστου',
      'Μιχάλης Ντούντρο',
      'Αρσινόη Πήλου',
    ],
    description: 'Η Αρκουδότρυπα είναι το απόλυτο βουκολικό ρομάντζο του 21ου αιώνα. Φωτεινό και αισιόδοξο, γκρεμίζει στερεότυπα και αντιστέκεται στον συντηρητισμό της',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/05/poster.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/arkoydotrypa-2025/',
    cinemas: [
      'Μακεδονικόν',
      'Απόλλων Θερινός',
    ],
    screenings: [
      {
        cinema: 'Μακεδονικόν',
        cinemaSlug: 'makedonikon',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '22:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '22:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '22:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '22:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '22:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '22:00',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '22:00',
            ],
          },
        ],
      },
      {
        cinema: 'Απόλλων Θερινός',
        cinemaSlug: 'apollon',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '22:30',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
    ],
  },
  {
    slug: 'in-the-grey-2026',
    title: 'Γκρίζα Ζώνη',
    originalTitle: 'In the Grey',
    year: 2026,
    durationMin: 98,
    genres: [
      'Δραματική',
      'Δράσης',
    ],
    rating: 6.5,
    director: 'Γκάι Ρίτσι',
    cast: [
      'Χένρι Κάβιλ',
      'Τζέικ Τζίλενχαλ',
      'Ροζαμάουντ Πάικ',
      'Έιζα Γκονσάλες',
      'Φίσερ Στίβενς',
      'Τζέισον Γουόνγκ',
      'Κάρλος Μπαρδέμ',
      'Έμετ Τζ. Σκάνλαν',
      'Κρίστιαν Οτσόα',
      'Ράνα Αλαμουντίν',
    ],
    description: 'Μια μυστική ομάδα κορυφαίων πρακτόρων ζει στη σκιά της παγκόσμιας ελίτ, έχοντας την ικανότητα να ασκεί εξουσία και επιρροή αλλά και να χειρίζεται αυτόματα',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/05/in-the-grey.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/in-the-grey-2026/',
    cinemas: [
      'Odeon Πλατεία',
    ],
    screenings: [
      {
        cinema: 'Odeon Πλατεία',
        cinemaSlug: 'odeon-plateia',
        hall: 'Αίθουσα 4',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '22:10',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '22:10',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '22:10',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '22:10',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '22:10',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '22:10',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
    ],
  },
  {
    slug: 'ellada-30-2026',
    title: 'Ελλάδα 3.0',
    year: 2026,
    durationMin: 88,
    genres: [
      'Ελληνική Ταινία',
      'Κωμωδία',
      'Μαύρη Κωμωδία',
    ],
    director: 'Μιχάλης Γιγιντής,',
    cast: [
      'Αντώνης Τσιοτσιόπουλος',
      'Θάνος Τοκάκης',
      'Κώστας Φυτίλης',
      'Γιώργος Χρυσοστόμου',
      'Αλέξανδρος Χρυσανθόπουλος',
      'Δάφνη Κιουρκτσόγλου',
      'Δημήτρης Δρόσος',
      'Αλίκη Αλεξανδράκη',
      'Σίμος Κακάλας',
      'Λευτέρης Πολυχρόνης',
    ],
    description: 'Για πρώτη φορά, τρεις κωμωδίες μικρού μήκους ενώνονται σε μία κοινή κινηματογραφική κυκλοφορία. Το «Ελλάδα 3.0» είναι ένα νέο project που φέρνει μαζί',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/05/30.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/ellada-30-2026/',
    cinemas: [
      'Ελληνίς (Θερινός)',
      'Βακούρα',
      'Options Μακεδονία (Πρώην Odeon)',
      'Village Cosmos',
    ],
    screenings: [
      {
        cinema: 'Ελληνίς (Θερινός)',
        cinemaSlug: 'ellinis',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '20:50',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '20:50',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '20:50',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '20:50',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '20:50',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '20:50',
            ],
          },
        ],
      },
      {
        cinema: 'Βακούρα',
        cinemaSlug: 'vakoura',
        hall: 'Αίθουσα 2',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '19:45',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '19:45',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '19:45',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '19:45',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '19:45',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '19:45',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '19:45',
            ],
          },
        ],
      },
      {
        cinema: 'Options Μακεδονία (Πρώην Odeon)',
        cinemaSlug: 'odeon-makedonia',
        hall: 'Αίθουσα 1',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '18:50',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '18:50',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '18:50',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '18:50',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '18:50',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '18:50',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '18:50',
            ],
          },
        ],
      },
      {
        cinema: 'Village Cosmos',
        cinemaSlug: 'village-cosmos',
        hall: 'Αίθουσα 1',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '21:45',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '21:45',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '21:45',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '21:45',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '21:45',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '21:45',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '23:00',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
    ],
  },
  {
    slug: 'un-poeta-2025',
    title: 'Ένας Ποιητής',
    originalTitle: 'Un poeta',
    year: 2025,
    durationMin: 123,
    genres: [
      'Δραματική',
      'Κωμωδία',
    ],
    rating: 7.9,
    director: 'Σιμόν Μέσα Σότο',
    cast: [
      'Ουμπεϊμάρ Ρίος',
      'Ρεμπέκα Αντράδε',
      'Γκιγιέρμο Καρδόνα',
      'Αλισον Κορέα',
    ],
    description: 'Ένας ηλικιωμένος ποιητής βρίσκει σκοπό να καθοδηγήσει την Γιούρλαντι, μια ταλαντούχα έφηβη, αν και το να την εκθέσει στον χώρο της ποίησης μπορεί να μην',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/05/un-poeta.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/un-poeta-2025/',
    cinemas: [
      'Μακεδονικόν',
    ],
    screenings: [
      {
        cinema: 'Μακεδονικόν',
        cinemaSlug: 'makedonikon',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '20:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '20:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '20:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '20:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '20:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '20:00',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '20:00',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
    ],
  },
  {
    slug: 'etymhgoria-2025',
    title: 'Η Ετυμηγορία',
    originalTitle: 'Re-Creation',
    year: 2025,
    durationMin: 89,
    genres: [
      'Δικαστική / Νομική',
      'Δραματική',
      'Μυστηρίου',
      'Ντοκιμαντέρ',
    ],
    rating: 5.7,
    director: 'Ντέιβιντ Μέριμαν,',
    cast: [
      'Βίκι Κριπς',
      'Κολμ Μίνεϊ',
      'Έινταν Γκίλεν',
      'Τζιμ Σέρινταν',
      'Τρίσταν Χίνιου',
      'Τζον Κόνορς',
      'Γκίλμπερτ Τζόνστον',
      'Έλενα Σπάουτζ',
      'Ζαχάρα Μουφίντ',
      'Μπρένταν Κόνροϊ',
    ],
    description: 'Με έξι υποψηφιότητες για Όσκαρ, ο Τζιμ Σέρινταν είναι ο σημαντικότερος Ιρλανδός σκηνοθέτης των τελευταίων 50 ετών και εμπνέεται πάντα από αληθινές',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/05/etymigoria-2026.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/etymhgoria-2025/',
    cinemas: [
      'Cine Άλεξ (Θερινός)',
      'Options Μακεδονία (Πρώην Odeon)',
      'Village Cosmos',
    ],
    screenings: [
      {
        cinema: 'Cine Άλεξ (Θερινός)',
        cinemaSlug: 'cine-alex',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '21:00',
            ],
          },
        ],
      },
      {
        cinema: 'Options Μακεδονία (Πρώην Odeon)',
        cinemaSlug: 'odeon-makedonia',
        hall: 'Αίθουσα 3',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '20:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '20:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '20:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '20:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '20:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '20:00',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '18:00',
            ],
          },
        ],
      },
      {
        cinema: 'Village Cosmos',
        cinemaSlug: 'village-cosmos',
        hall: 'Αίθουσα 2',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '19:40',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '19:40',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '19:40',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '19:40',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '19:40',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '19:40',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '19:15',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
    ],
  },
  {
    slug: 'zoi-kai-ta-zoakia-tis-2026',
    title: 'Η Ζόι και τα Ζωάκια της',
    originalTitle: 'Evolution',
    year: 2026,
    durationMin: 94,
    genres: [
      'Sci-Fi',
      'Κινούμενα Σχέδια',
      'Κωμωδία',
      'Φαντασίας',
    ],
    director: 'Χούλιο Σότο Γκουρπίντε,',
    cast: [
      'Με τις φωνές των: Λητώ Αμπατζή',
      'Σοφία Παναηλίδου',
      'Ανδρέας Ευαγγελάτος',
      'Γιάννης Τσιούτσιας',
      'Χρύσα Παπαδοπούλου',
      'Χρήστος Συριώτης',
      'Νέστορας Κοψιδάς',
      'Γιάννης Υφαντής',
      'Γεωργία Ιωαννίδου',
      'Κωνσταντίνος Ρεπάνης',
      'Βασίλης Παπαστάθης',
    ],
    description: 'Όταν μια εξωγήινη ουσία αναμειγνύει το DNA της Ζόι με εκείνο των εξωτικών κατοικιδίων της, ξεκινά μια ξεκαρδιστική περιπέτεια όπου οι άνθρωποι γίνονται',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/05/evolution.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/zoi-kai-ta-zoakia-tis-2026/',
    cinemas: [
      'Odeon Πλατεία',
      'Options Μακεδονία (Πρώην Odeon)',
      'Cineplexx One Salonica',
      'Village Cosmos',
    ],
    screenings: [
      {
        cinema: 'Odeon Πλατεία',
        cinemaSlug: 'odeon-plateia',
        hall: 'Αίθουσα 4 (Μεταγλ.)',
        sessions: [
          {
            date: '2026-06-06',
            times: [
              '17:50',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '17:50',
            ],
          },
        ],
      },
      {
        cinema: 'Options Μακεδονία (Πρώην Odeon)',
        cinemaSlug: 'odeon-makedonia',
        hall: 'Αίθουσα 5 (Μεταγλ.)',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '18:20',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '18:20',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '18:20',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '18:20',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '18:20',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '18:20',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '18:20',
            ],
          },
        ],
      },
      {
        cinema: 'Cineplexx One Salonica',
        cinemaSlug: 'one-salonica',
        hall: 'Αίθουσα 6 (Μεταγλ.)',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '18:30',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '18:30',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '18:30',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '18:30',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '18:30',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '18:30',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '18:30',
            ],
          },
        ],
      },
      {
        cinema: 'Village Cosmos',
        cinemaSlug: 'village-cosmos',
        hall: 'Αίθουσα 2 (Μεταγλ.)',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '17:00',
              '17:50',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '17:00',
              '17:50',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '15:15',
              '17:30',
              '17:50',
              '18:30',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '15:15',
              '17:30',
              '17:50',
              '18:30',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '17:00',
              '17:50',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '17:00',
              '17:50',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '17:00',
              '17:50',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
    ],
  },
  {
    slug: 'animal-farm-2026',
    title: 'Η Φάρμα των Ζώων',
    originalTitle: 'Animal Farm',
    year: 2026,
    durationMin: 96,
    genres: [
      'Δραματική',
      'Κινούμενα Σχέδια',
      'Μαύρη Κωμωδία',
      'Οικογενειακή',
      'Περιπέτεια',
      'Φαντασίας',
    ],
    rating: 2.7,
    director: 'Άντι Σέρκις',
    cast: [
      'Με τις φωνές των: Δημήτρης Δρίβας',
      'Ραφαέλ Αριστοτέλους',
      'Δημήτρης Πίτσος',
      'Ιωάννα Καραθανάση',
      'Τάκης Σακελλαρίου',
      'Στρατής Χατζησταματίου',
      'Μαρία Γκιώνη',
      'Μαριλένα Λιακοπούλου',
      'Θανάσης Χαλκιάς',
      'Βαγγέλης Μάγειρος',
    ],
    description: 'Όταν τα ζώα μιας φάρμας αποφασίζουν να πάρουν τη ζωή τους στα χέρια τους, διώχνουν τον άνθρωπο ιδιοκτήτη και δημιουργούν μια νέα κοινότητα όπου όλοι είναι',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/06/animal-farm.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/animal-farm-2026/',
    cinemas: [
      'Odeon Πλατεία',
      'Options Μακεδονία (Πρώην Odeon)',
      'Cineplexx One Salonica',
      'Village Cosmos',
    ],
    screenings: [
      {
        cinema: 'Odeon Πλατεία',
        cinemaSlug: 'odeon-plateia',
        hall: 'Αίθουσα 1 (Μεταγλ.)',
        sessions: [
          {
            date: '2026-06-06',
            times: [
              '18:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '18:00',
            ],
          },
        ],
      },
      {
        cinema: 'Options Μακεδονία (Πρώην Odeon)',
        cinemaSlug: 'odeon-makedonia',
        hall: 'Αίθουσα 2 (Μεταγλ.)',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '18:10',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '18:10',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '18:10',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '18:10',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '18:10',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '18:10',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '18:10',
            ],
          },
        ],
      },
      {
        cinema: 'Cineplexx One Salonica',
        cinemaSlug: 'one-salonica',
        hall: 'Αίθουσα 2 (Μεταγλ.)',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '17:45',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '17:45',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '17:45',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '17:45',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '17:45',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '17:45',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '17:45',
            ],
          },
        ],
      },
      {
        cinema: 'Village Cosmos',
        cinemaSlug: 'village-cosmos',
        hall: 'Αίθουσα 2 (Μεταγλ.)',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '17:20',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '17:20',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '16:15',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '16:15',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '17:20',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '17:20',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
    ],
  },
  {
    slug: 'imera-apokalipsis-2026',
    title: 'Ημέρα Αποκάλυψης',
    originalTitle: 'Disclosure Day',
    year: 2026,
    durationMin: 145,
    genres: [
      'Sci-Fi',
      'Δραματική',
      'Επική Περιπέτεια',
    ],
    director: 'Στίβεν Σπίλμπεργκ',
    cast: [
      'Έμιλι Μπλαντ',
      'Τζος Ο\' Κόνορ',
      'Κόλιν Φερθ',
      'Ιβ Χιούσον',
      'Κόλμαν Ντομίνγκο',
      'Γουάιατ Ράσελ',
      'Χένρι Λόιντ-Χιουζ',
      'Έλιζαμπεθ Μάρβελ',
      'Μακένα Μπρίτζερ',
      'Μάικλ Γκαστόν',
    ],
    description: 'Αν ανακάλυπτες ότι δεν είμαστε μόνοι, αν κάποιος σου το έδειχνε, σου το αποδείκνυε, θα σε τρομοκρατούσε; Αυτό το καλοκαίρι, η αλήθεια ανήκει σε επτά',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/05/disclosure-day.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/imera-apokalipsis-2026/',
    cinemas: [
      'Ελληνίς (Θερινός)',
      'Odeon Πλατεία',
      'Options Μακεδονία (Πρώην Odeon)',
      'Cineplexx One Salonica',
      'Village Cosmos',
      'Σινέ Πανόραμα (Θερινός)',
    ],
    screenings: [
      {
        cinema: 'Ελληνίς (Θερινός)',
        cinemaSlug: 'ellinis',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-10',
            times: [
              '21:00',
            ],
          },
        ],
      },
      {
        cinema: 'Odeon Πλατεία',
        cinemaSlug: 'odeon-plateia',
        hall: 'Αίθουσα 1',
        sessions: [
          {
            date: '2026-06-10',
            times: [
              '19:00',
              '20:30',
              '22:00',
            ],
          },
        ],
      },
      {
        cinema: 'Options Μακεδονία (Πρώην Odeon)',
        cinemaSlug: 'odeon-makedonia',
        hall: 'Αίθουσα 3',
        sessions: [
          {
            date: '2026-06-10',
            times: [
              '18:30',
              '20:00',
              '21:30',
            ],
          },
        ],
      },
      {
        cinema: 'Cineplexx One Salonica',
        cinemaSlug: 'one-salonica',
        hall: 'Αίθουσα 1 IMAX',
        sessions: [
          {
            date: '2026-06-10',
            times: [
              '20:00',
              '21:00',
              '22:00',
              '22:50',
            ],
          },
        ],
      },
      {
        cinema: 'Village Cosmos',
        cinemaSlug: 'village-cosmos',
        hall: 'Αίθουσα 6 Vmax',
        sessions: [
          {
            date: '2026-06-10',
            times: [
              '18:30',
              '19:15',
              '21:15',
              '22:00',
              '22:20',
            ],
          },
        ],
      },
      {
        cinema: 'Σινέ Πανόραμα (Θερινός)',
        cinemaSlug: 'cine-panorama',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-11',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-12',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-13',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-14',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-15',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-16',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-17',
            times: [
              '21:00',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-10',
      '2026-06-11',
      '2026-06-12',
      '2026-06-13',
      '2026-06-14',
      '2026-06-15',
      '2026-06-16',
      '2026-06-17',
    ],
  },
  {
    slug: 'mikres-anases-2025',
    title: 'Μικρές Ανάσες',
    year: 2025,
    durationMin: 92,
    genres: [
      'Δραματική',
      'Ελληνική Ταινία',
    ],
    director: 'Αμέρισσα Μπάστα',
    cast: [
      'Ελίνα Τσιορμπατζή',
      'Τζέο Πακίτσας',
      'Αντώνης Τσιοτσιόπουλος',
      'Λούλι Μπίτρι',
      'Περικλής Καραγεώργας',
      'Δημήτρης Κίτσος',
      'Μαργαρίτα Αλεξιάδη',
      'Γιώργος Πυρπασόπουλος',
      'Μαρίνα Μακρή',
      'Μαρία Καλλιμάνη',
    ],
    description: 'Η Λένα είναι είκοσι χρονών και ζει με την οικογένειά της σε μια γειτονιά της Αθήνας. Δουλεύει σε ένα τοπικό σούπερ μάρκετ και τα βγάζει δύσκολα πέρα μέσα',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/06/poster-1.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/mikres-anases-2025/',
    cinemas: [
      'Απόλλων Θερινός',
    ],
    screenings: [
      {
        cinema: 'Απόλλων Θερινός',
        cinemaSlug: 'apollon',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '20:45',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '20:45',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '20:45',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '20:45',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '20:45',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '20:45',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-09',
      '2026-06-10',
    ],
  },
  {
    slug: 'star-wars-the-mandalorian-and-grogu-2026',
    title: 'Ο Πόλεμος των Άστρων',
    originalTitle: 'Star Wars: The Mandalorian and Grogu',
    year: 2026,
    durationMin: 132,
    genres: [
      'Sci-Fi',
      'Δράσης',
      'Επική Περιπέτεια',
      'Οικογενειακή',
      'Περιπέτεια',
      'Φαντασίας',
    ],
    director: 'Τζον Φεβρώ',
    cast: [
      'Πέδρο Πασκάλ',
      'Μάρτιν Σκορτσέζε (Ardennian Fry Cook)',
      'Σιγκούρνεϊ Γουίβερ',
      'Τζέρεμι Άλεν Γουάιτ',
      'Μάθιου Γουίλιγκ',
      'Στηβ Μπλουμ',
      'Χέμκι Μαντέρα',
      'Λόντον Σταμπλφίλντ',
      'Μάιλς Χουμφους',
      'Έβαν Σαφραν',
      'Πόρτσια Χάρις',
      'Κρίστοφερ Άλαν Ρόμπινσον',
      'Τζόνι Κόιν',
    ],
    description: 'Η κακή Αυτοκρατορία έχει καταρρεύσει και οι αυτοκρατορικοί πολέμαρχοι παραμένουν διάσπαρτοι σε όλον το γαλαξία. Καθώς η νεοσύστατη Καινούργια Δημοκρατία',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/04/Star-Wars-The-Mandalorian-and-Grogu.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/star-wars-the-mandalorian-and-grogu-2026/',
    cinemas: [
      'Options Μακεδονία (Πρώην Odeon)',
      'Cineplexx One Salonica',
      'Village Cosmos',
    ],
    screenings: [
      {
        cinema: 'Options Μακεδονία (Πρώην Odeon)',
        cinemaSlug: 'odeon-makedonia',
        hall: 'Αίθουσα 3',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '22:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '22:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '22:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '22:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '22:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '22:00',
            ],
          },
        ],
      },
      {
        cinema: 'Cineplexx One Salonica',
        cinemaSlug: 'one-salonica',
        hall: 'Αίθουσα 7',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '22:15',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '22:15',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '22:15',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '22:15',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '22:15',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '22:15',
            ],
          },
        ],
      },
      {
        cinema: 'Village Cosmos',
        cinemaSlug: 'village-cosmos',
        hall: 'Αίθουσα 1',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '17:30',
              '22:45',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '17:30',
              '22:45',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '15:10',
              '17:15',
              '22:45',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '15:10',
              '17:15',
              '22:45',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '17:30',
              '22:45',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '17:30',
              '22:45',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '17:30',
              '22:45',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
    ],
  },
  {
    slug: 'den-sidste-viking-2025',
    title: 'Ο Τελευταίος Βίκινγκ',
    originalTitle: 'The Last Viking/Den sidste viking',
    year: 2025,
    durationMin: 116,
    genres: [
      'Δραματική',
      'Κωμωδία',
      'Μαύρη Κωμωδία',
    ],
    rating: 7.2,
    director: 'Αντερς Τόμας Γένσεν',
    cast: [
      'Νικολάι Λίε Κάας',
      'Μαντς Μίκελσεν',
      'Σόφι Γκρόμπολ',
      'Σόρεν Μάλινγκ',
      'Μπόντιλ Γιόργκενσεν',
      'Λαρς Μπρίγκμαν',
      'Κάρντο Ραζάζι',
    ],
    description: 'Αφού εκτίσει δεκατέσσερα χρόνια φυλάκισης για ληστεία, ο Άνκερ αποφυλακίζεται και ξανασμίγει με τον ψυχικά άρρωστο αδελφό του Μάνφρεντ, ο οποίος ειναι',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/05/den-sidste-viking.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/den-sidste-viking-2025/',
    cinemas: [
      'Σινέ Ναταλί (Θερινός)',
      'Βακούρα',
    ],
    screenings: [
      {
        cinema: 'Σινέ Ναταλί (Θερινός)',
        cinemaSlug: 'natali',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '23:00',
            ],
          },
        ],
      },
      {
        cinema: 'Βακούρα',
        cinemaSlug: 'vakoura',
        hall: 'Αίθουσα 2',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '21:30',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
    ],
  },
  {
    slug: 'psaromourmouras-2026',
    title: 'Ο Ψαρομουρμούρας',
    originalTitle: 'The Pout-Pout Fish',
    year: 2026,
    durationMin: 92,
    genres: [
      'Κινούμενα Σχέδια',
      'Κωμωδία',
      'Οικογενειακή',
      'Περιπέτεια',
      'Φαντασίας',
    ],
    director: 'Ρικάρντ Κουσό,',
    cast: [
      'Με τις φωνές των: Θανάσης Κουρλαμπάς',
      'Λυδία Σγουράκη',
      'Νίκος Παπαδόπουλος',
      'Ησαΐας Ματιάμπα',
      'Μιχάλης Μιχαλακίδης',
      'Βαγγέλης Στρατηγάκος',
      'Βούλα Κώστα',
      'Γιώργος Σκουφής',
      'Λητώ Αμπατζή',
      'Έλενα Δελακούρα και Μαρία Ζερβού',
      'ενώ συμμετέχουν και οι μικροί Κωνσταντίνος Ανδριόπουλος',
      'Αχιλλέας Κουτσούκης και Αλεξάνδρα Ηλία',
    ],
    description: 'Ένα χαμόγελο δεν έβλαψε ποτέ κανέναν. Δύο υδρόβια πλάσματα που δεν ταιριάζουν πουθενά ξεκινούν ένα απίθανο ταξίδι για να σώσουν τον τόπο τους. Ζώντας σε',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/05/the-pout-pout-fish-1.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/psaromourmouras-2026/',
    cinemas: [
      'Options Μακεδονία (Πρώην Odeon)',
      'Village Cosmos',
    ],
    screenings: [
      {
        cinema: 'Options Μακεδονία (Πρώην Odeon)',
        cinemaSlug: 'odeon-makedonia',
        hall: 'Αίθουσα 3 (Μεταγλ.)',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '18:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '18:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '18:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '18:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '18:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '18:00',
            ],
          },
        ],
      },
      {
        cinema: 'Village Cosmos',
        cinemaSlug: 'village-cosmos',
        hall: 'Αίθουσα 9 – VKids (Μεταγλ.)',
        sessions: [
          {
            date: '2026-06-06',
            times: [
              '15:30',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '15:30',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
    ],
  },
  {
    slug: 'the-christophers-2026',
    title: 'Οι Κρίστοφερ',
    originalTitle: 'The Christophers',
    year: 2026,
    durationMin: 100,
    genres: [
      'Δραματική',
      'Μαύρη Κωμωδία',
    ],
    rating: 6.8,
    director: 'Στίβεν Σόντερμπεργκ',
    cast: [
      'Μικαέλα Κόελ',
      'Ίαν ΜακΚέλεν',
      'Τζέσικα Γκάνινγκ',
      'Τζέιμς Κόρντεν',
      'Φέρντι Ρόμπερτς',
      'Τίλι Μπότσφορντ',
      'Λούσι ΜακΚόρμικ',
      'Λε Φιλ',
      'Ντάνιελ Φερν',
      'Ντμίτρι Προκόπιεφ',
    ],
    description: 'Ο βραβευμένος με Όσκαρ® σκηνοθέτης Στήβεν Σοντερμπεργκ επιστρέφει με μία απολαυστική ταινία χαρακτήρων, Οι Κρίστοφερ: μια πνευματώδη, σκοτεινά κωμική',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/05/the-christophers.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/the-christophers-2026/',
    cinemas: [
      'Μακεδονικόν',
      'Cine Άλεξ (Θερινός)',
    ],
    screenings: [
      {
        cinema: 'Μακεδονικόν',
        cinemaSlug: 'makedonikon',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '18:15',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '18:15',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '18:15',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '18:15',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '18:15',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '18:15',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '18:15',
            ],
          },
        ],
      },
      {
        cinema: 'Cine Άλεξ (Θερινός)',
        cinemaSlug: 'cine-alex',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '23:00',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
    ],
  },
  {
    slug: 'masters-of-the-universe-2026',
    title: 'Οι Κυρίαρχοι του Σύμπαντος',
    originalTitle: 'Masters of the Universe',
    year: 2026,
    durationMin: 141,
    genres: [
      'Sci-Fi',
      'Δράσης',
      'Περιπέτεια',
      'Σούπερ Ήρωες',
      'Φαντασίας',
    ],
    rating: 6.9,
    director: 'Τράβις Νάιτ',
    cast: [
      'Νίκολας Γκαλιτζίν',
      'Καμίλα Μέντες',
      'Άλισον Μπρι',
      'Τζέιμς Πιούρφοϊ',
      'Μορένα Μπακαρίν',
      'Γιοχάνες Χάουκουρ Γιοχάνεσον',
      'Κρίστεν Γουίγκ',
      'Τζάρεντ Λέτο',
      'Ίντρις Έλμπα',
      'Σαμ Σι Γουίλσον',
    ],
    description: 'Στην ταινία Οι Κυρίαρχοι του Σύμπαντος, ο σκηνοθέτης Τράβις Νάιτ επαναφέρει το θρυλικό franchise στη μεγάλη οθόνη σε αυτήν την επική περιπέτεια. Μετά από',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/05/masters-of-the-universe.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/masters-of-the-universe-2026/',
    cinemas: [
      'Odeon Πλατεία',
      'Options Μακεδονία (Πρώην Odeon)',
      'Cineplexx One Salonica',
      'Village Cosmos',
    ],
    screenings: [
      {
        cinema: 'Odeon Πλατεία',
        cinemaSlug: 'odeon-plateia',
        hall: 'Αίθουσα 2',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '19:10',
              '21:50',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '19:10',
              '21:50',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '19:10',
              '21:50',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '19:10',
              '21:50',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '19:10',
              '21:50',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '19:10',
              '21:50',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '19:10',
            ],
          },
        ],
      },
      {
        cinema: 'Options Μακεδονία (Πρώην Odeon)',
        cinemaSlug: 'odeon-makedonia',
        hall: 'Αίθουσα 9',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '20:40',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '20:40',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '20:40',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '20:40',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '20:40',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '20:40',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '20:40',
            ],
          },
        ],
      },
      {
        cinema: 'Cineplexx One Salonica',
        cinemaSlug: 'one-salonica',
        hall: 'Αίθουσα 1 IMAX',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '18:15',
              '19:15',
              '21:00',
              '22:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '18:15',
              '19:15',
              '21:00',
              '22:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '18:15',
              '19:15',
              '21:00',
              '22:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '18:15',
              '19:15',
              '21:00',
              '22:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '18:15',
              '19:15',
              '21:00',
              '22:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '18:15',
              '19:15',
              '21:00',
              '22:00',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '18:15',
              '19:15',
            ],
          },
        ],
      },
      {
        cinema: 'Village Cosmos',
        cinemaSlug: 'village-cosmos',
        hall: 'Αίθουσα 3',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '17:45',
              '18:45',
              '19:10',
              '19:30',
              '20:50',
              '22:00',
              '22:50',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '17:45',
              '18:45',
              '19:10',
              '19:30',
              '20:50',
              '22:00',
              '22:50',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '15:30',
              '16:30',
              '18:45',
              '19:10',
              '19:30',
              '20:50',
              '22:00',
              '22:50',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '15:30',
              '16:30',
              '18:45',
              '19:10',
              '19:30',
              '20:50',
              '22:00',
              '22:50',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '17:45',
              '18:45',
              '19:10',
              '19:30',
              '20:50',
              '22:00',
              '22:50',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '17:45',
              '18:45',
              '19:10',
              '19:30',
              '20:50',
              '22:00',
              '22:50',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '17:45',
              '18:45',
              '19:30',
              '20:50',
              '21:45',
              '22:50',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
    ],
  },
  {
    slug: 'amarga-navidad-2026',
    title: 'Πικρές Γιορτές',
    originalTitle: 'Bitter Christmas / Amarga Navidad',
    year: 2026,
    durationMin: 112,
    genres: [
      'Δραματική',
      'Κομεντί',
    ],
    rating: 6.5,
    director: 'Πέδρο Αλμοδόβαρ',
    cast: [
      'Μπάρμπαρα Λένι',
      'Λεονάρντο Σμπαράλια',
      'Αϊτάνα Σάντσεθ-Χιχόν',
      'Βικτόρια Λουένγκο',
      'Πάτρικ Κριάδο',
      'Μιλένα Σμιτ',
      'Κιμ Γκουτιέρες',
    ],
    description: 'Ο Πέδρο Αλμοδόβαρ επιστρέφει στην Ισπανία με μια γλυκόπικρη ιστορία για τη ζωή και το σινεμά. Η Έλσα, διαφημίστρια με κρίσεις πανικού, αμφιταλαντεύεται',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/06/amarga-navidad.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/amarga-navidad-2026/',
    cinemas: [
      'Σινέ Ναταλί (Θερινός)',
      'Odeon Πλατεία',
      'Options Μακεδονία (Πρώην Odeon)',
      'Village Cosmos',
    ],
    screenings: [
      {
        cinema: 'Σινέ Ναταλί (Θερινός)',
        cinemaSlug: 'natali',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '21:00',
            ],
          },
        ],
      },
      {
        cinema: 'Odeon Πλατεία',
        cinemaSlug: 'odeon-plateia',
        hall: 'Αίθουσα 4',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '19:50',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '19:50',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '19:50',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '19:50',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '19:50',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '19:50',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '19:50',
            ],
          },
        ],
      },
      {
        cinema: 'Options Μακεδονία (Πρώην Odeon)',
        cinemaSlug: 'odeon-makedonia',
        hall: 'Αίθουσα 5',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '20:30',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '20:30',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '20:30',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '20:30',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '20:30',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '20:30',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '20:30',
            ],
          },
        ],
      },
      {
        cinema: 'Village Cosmos',
        cinemaSlug: 'village-cosmos',
        hall: 'Αίθουσα 1',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '20:30',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '20:30',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '20:30',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '20:30',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '20:30',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '20:30',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '20:30',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
    ],
  },
  {
    slug: 'backrooms-2026',
    title: 'Backrooms',
    year: 2026,
    durationMin: 110,
    genres: [
      'Sci-Fi',
      'Τρόμου',
      'Ψυχολογικό Δράμα',
    ],
    rating: 7.1,
    director: 'Κέιν Πάρσονς',
    cast: [
      'Τσιούετελ Έτζιοφορ',
      'Ρενάτε Ράινσβε',
      'Μαρκ Ντούπλας',
      'Φιν Μπένετ',
      'Λουκίτα Μάξγουελ',
      'Άβαν Τζόγια',
      'Ρόμπερτ Μπομπρότσκι',
      'Έμπερ Άμπροουζ',
      'Κρίστα Κόσονεν',
      'Φίλιπ Γκρέιντζερ',
    ],
    description: '“Δεν θα’ πρεπε να είσαι εδώ.” Μια παράξενη πόρτα εμφανίζεται στο υπόγειο μιας έκθεσης επίπλων. Αφότου ο ασθενής μιας θεραπεύτριας εξαφανίζεται σε μια',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/05/backrooms.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/backrooms-2026/',
    cinemas: [
      'Αύρα (Θερινός)',
      'Βακούρα',
      'Odeon Πλατεία',
      'Options Μακεδονία (Πρώην Odeon)',
      'Cineplexx One Salonica',
      'Village Cosmos',
    ],
    screenings: [
      {
        cinema: 'Αύρα (Θερινός)',
        cinemaSlug: 'cine-avra',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '23:00',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '23:00',
            ],
          },
        ],
      },
      {
        cinema: 'Βακούρα',
        cinemaSlug: 'vakoura',
        hall: 'Αίθουσα 1',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '21:30',
            ],
          },
        ],
      },
      {
        cinema: 'Odeon Πλατεία',
        cinemaSlug: 'odeon-plateia',
        hall: 'Αίθουσα 2',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '19:00',
              '21:20',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '21:50',
            ],
          },
        ],
      },
      {
        cinema: 'Options Μακεδονία (Πρώην Odeon)',
        cinemaSlug: 'odeon-makedonia',
        hall: 'Αίθουσα 1',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '21:00',
            ],
          },
        ],
      },
      {
        cinema: 'Cineplexx One Salonica',
        cinemaSlug: 'one-salonica',
        hall: 'Αίθουσα 5',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '19:00',
              '20:20',
              '21:30',
              '22:30',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '19:00',
              '20:20',
              '21:30',
              '22:30',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '19:00',
              '20:20',
              '21:30',
              '22:30',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '19:00',
              '20:20',
              '21:30',
              '22:30',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '19:00',
              '20:20',
              '21:30',
              '22:30',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '19:00',
              '20:20',
              '21:30',
              '22:30',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '19:00',
              '20:20',
              '21:30',
              '22:30',
            ],
          },
        ],
      },
      {
        cinema: 'Village Cosmos',
        cinemaSlug: 'village-cosmos',
        hall: 'Αίθουσα 1',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '17:30',
              '21:30',
              '22:20',
              '23:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '21:30',
              '22:20',
              '23:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '16:40',
              '21:30',
              '22:20',
              '23:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '16:40',
              '21:30',
              '22:20',
              '23:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '19:50',
              '21:30',
              '22:20',
              '23:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '19:50',
              '21:30',
              '22:20',
              '23:00',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '19:50',
              '22:20',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
    ],
  },
  {
    slug: 'michael-2026',
    title: 'Michael',
    year: 2026,
    durationMin: 127,
    genres: [
      'Βιογραφική',
      'Δραματική',
      'Ιστορική',
    ],
    rating: 7.7,
    director: 'Αντουάν Φουκουά',
    cast: [
      'Τζαφάρ Τζάκσον',
      'Τζουλιάνο Βάλντι',
      'Λία Λονγκ',
      'Κόλμαν Ντομίγκο',
      'Μάιλς Τέλερ',
      'Κέντρικ Σάμσον',
      'Κατ Γκράχαμ',
      'Λόρα Χάριερ',
      'Τζέσικα Σούλα',
      'Μάικλ ΜακΝιλ',
      'Έρικ Λάνσεθ',
      'Ντέρεκ λιουκ',
      'Λάρεντζ Τέιτ',
    ],
    description: 'Η ταινία Michael απεικονίζει σε βάθος τη ζωή και την κληρονομιά ενός από τους πιο επιδραστικούς καλλιτέχνες που γνώρισε ο κόσμος. Η βιογραφία αφηγείται',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/04/Michael.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/michael-2026/',
    cinemas: [
      'Βακούρα',
      'Options Μακεδονία (Πρώην Odeon)',
      'Cineplexx One Salonica',
      'Σινέ Πυλαία (Θερινός)',
    ],
    screenings: [
      {
        cinema: 'Βακούρα',
        cinemaSlug: 'vakoura',
        hall: 'Αίθουσα 1',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '19:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '19:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '19:00',
            ],
          },
        ],
      },
      {
        cinema: 'Options Μακεδονία (Πρώην Odeon)',
        cinemaSlug: 'odeon-makedonia',
        hall: 'Αίθουσα 4',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '21:30',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '18:50',
              '21:30',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '18:50',
              '21:30',
            ],
          },
        ],
      },
      {
        cinema: 'Cineplexx One Salonica',
        cinemaSlug: 'one-salonica',
        hall: 'Αίθουσα 5',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '21:15',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '21:15',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '21:15',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '21:15',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '21:15',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '21:15',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '21:15',
            ],
          },
        ],
      },
      {
        cinema: 'Σινέ Πυλαία (Θερινός)',
        cinemaSlug: 'cine-pilaia',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-16',
            times: [
              '21:00',
            ],
          },
          {
            date: '2026-06-17',
            times: [
              '21:00',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
      '2026-06-16',
      '2026-06-17',
    ],
  },
  {
    slug: 'scary-movie-2026',
    title: 'Scary Movie 6',
    year: 2026,
    durationMin: 95,
    genres: [
      'Κωμωδία',
      'Μαύρη Κωμωδία',
      'Τρόμου',
    ],
    director: 'Μάικλ Τίντες',
    cast: [
      'Μάρλον Ουάιανς',
      'Σον Ουάιανς',
      'Άννα Φάρις',
      'Ρετζίνα Χολ',
      'Ντέιμον Ουάιανς Τζούνιορ',
      'Γκρεγκ Ουάιανς',
      'Κιμ Ουάιανς',
      'Μπένι Ζίλκε',
      'Κάμερον Σκοτ Ρόμπερτς',
      'Σέρι Οτέρι',
    ],
    description: 'Είκοσι έξι χρόνια μετά την απόδρασή τους από έναν ύποπτα γνωστό μασκοφόρο δολοφόνο («Ghostface»), οι Βασικοί Τέσσερις βρίσκονται και πάλι στο στόχαστρο',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/05/scary-movie.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/scary-movie-2026/',
    cinemas: [
      'Ελληνίς (Θερινός)',
      'Odeon Πλατεία',
      'Options Μακεδονία (Πρώην Odeon)',
      'Cineplexx One Salonica',
      'Village Cosmos',
    ],
    screenings: [
      {
        cinema: 'Ελληνίς (Θερινός)',
        cinemaSlug: 'ellinis',
        hall: undefined,
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '22:40',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '22:40',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '22:40',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '22:40',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '22:40',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '22:40',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '23:30',
            ],
          },
        ],
      },
      {
        cinema: 'Odeon Πλατεία',
        cinemaSlug: 'odeon-plateia',
        hall: 'Αίθουσα 1',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '20:00',
              '22:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '20:00',
              '22:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '20:00',
              '22:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '20:00',
              '22:00',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '20:00',
              '22:00',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '20:00',
              '22:00',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '22:10',
            ],
          },
        ],
      },
      {
        cinema: 'Options Μακεδονία (Πρώην Odeon)',
        cinemaSlug: 'odeon-makedonia',
        hall: 'Αίθουσα 2',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '20:20',
              '22:30',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '20:20',
              '22:30',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '20:20',
              '22:30',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '20:20',
              '22:30',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '20:20',
              '22:30',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '20:20',
              '22:30',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '20:20',
              '22:30',
            ],
          },
        ],
      },
      {
        cinema: 'Cineplexx One Salonica',
        cinemaSlug: 'one-salonica',
        hall: 'Αίθουσα 2',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '18:45',
              '19:45',
              '20:45',
              '21:45',
              '22:45',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '18:45',
              '19:45',
              '20:45',
              '21:45',
              '22:45',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '18:45',
              '19:45',
              '20:45',
              '21:45',
              '22:45',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '18:45',
              '19:45',
              '20:45',
              '21:45',
              '22:45',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '18:45',
              '19:45',
              '20:45',
              '21:45',
              '22:45',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '18:45',
              '19:45',
              '20:45',
              '21:45',
              '22:45',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '18:45',
              '19:45',
              '20:45',
              '21:45',
              '22:45',
            ],
          },
        ],
      },
      {
        cinema: 'Village Cosmos',
        cinemaSlug: 'village-cosmos',
        hall: 'Αίθουσα 2',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '17:15',
              '19:15',
              '20:20',
              '21:15',
              '22:10',
              '22:30',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '17:15',
              '18:00',
              '19:15',
              '20:20',
              '21:15',
              '22:10',
              '22:30',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '17:00',
              '18:00',
              '19:15',
              '20:20',
              '21:15',
              '22:10',
              '22:30',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '17:00',
              '18:00',
              '19:15',
              '20:20',
              '21:15',
              '22:10',
              '22:30',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '17:15',
              '18:00',
              '19:15',
              '20:20',
              '21:15',
              '22:10',
              '22:30',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '17:15',
              '18:00',
              '19:15',
              '20:20',
              '21:15',
              '22:10',
              '22:30',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '17:15',
              '18:00',
              '20:20',
              '21:30',
              '22:30',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
    ],
  },
  {
    slug: 'super-mario-galaxy-tainia-2026',
    title: 'Super Mario Galaxy η Ταινία',
    originalTitle: 'The Super Mario Galaxy Movie',
    year: 2026,
    durationMin: 98,
    genres: [
      'Επική Περιπέτεια',
      'Κινούμενα Σχέδια',
      'Κωμωδία',
      'Οικογενειακή',
      'Περιπέτεια',
      'Σούπερ Ήρωες',
      'Φαντασίας',
    ],
    rating: 6.3,
    director: 'Άαρον Χόβαθ,',
    cast: [
      'Με τις φωνές των: Κωνσταντίνος Λάγκος',
      'Βασίλης Παπαστάθης',
      'Στεφανία Φιλιάδη ',
      'Κωνσταντίνος Κουνέλλας',
      'Βασίλης Αξιώτης',
      'Αρετή Πασχάλη',
      'Θάνος Λέκκας',
      'Πέτρος Δαμουλής',
      'Κατερίνα Γκίργκις',
      'Δημήτρης Σάρλος',
      'Γιώργος Λιάντος',
      'Βαγγέλης Ζάπας',
      'Γιάννης Τσούτσιας',
      'Έλενα Παππά',
      'Αλεξάνδρα Ηλία',
      'Αφροδίτη Λουκάτου',
      'Ειρήνη Στελλούδη',
      'Ίωνας Σουβατζόγλου',
      'Θάνος Σεϊμένης',
      'Σάββας Παπαδόπουλος',
    ],
    description: 'O Γαλαξίας περιμένει. Ο Μάριο και ο Λουίτζι μαζί με την πριγκίπισσα Πιτς ξεκινούν μια περιπέτεια στα πέρατα του διαστήματος και σε όλο τον γαλαξία. Εκεί',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/03/Super-Mario-Galaxy-tainia.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/super-mario-galaxy-tainia-2026/',
    cinemas: [
      'Options Μακεδονία (Πρώην Odeon)',
      'Cineplexx One Salonica',
      'Village Cosmos',
      'Σινέ Ωραιόκαστρο (Θερινός)',
    ],
    screenings: [
      {
        cinema: 'Options Μακεδονία (Πρώην Odeon)',
        cinemaSlug: 'odeon-makedonia',
        hall: 'Αίθουσα 9 (Μεταγλ.)',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '18:30',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '18:30',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '18:30',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '18:30',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '18:30',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '18:30',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '18:30',
            ],
          },
        ],
      },
      {
        cinema: 'Cineplexx One Salonica',
        cinemaSlug: 'one-salonica',
        hall: 'Αίθουσα 4',
        sessions: [
          {
            date: '2026-06-06',
            times: [
              '17:15',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '17:15',
            ],
          },
        ],
      },
      {
        cinema: 'Village Cosmos',
        cinemaSlug: 'village-cosmos',
        hall: 'Αίθουσα 8 (Μεταγλ.)',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '20:15',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '20:15',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '15:00',
              '20:15',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '15:00',
              '20:15',
            ],
          },
          {
            date: '2026-06-08',
            times: [
              '17:20',
              '20:15',
            ],
          },
          {
            date: '2026-06-09',
            times: [
              '17:20',
              '20:15',
            ],
          },
          {
            date: '2026-06-10',
            times: [
              '17:20',
              '20:15',
            ],
          },
        ],
      },
      {
        cinema: 'Σινέ Ωραιόκαστρο (Θερινός)',
        cinemaSlug: 'cine-oraiokastro',
        hall: '(Μεταγλ.)',
        sessions: [
          {
            date: '2026-06-11',
            times: [
              '21:15',
            ],
          },
          {
            date: '2026-06-12',
            times: [
              '21:15',
            ],
          },
          {
            date: '2026-06-13',
            times: [
              '21:15',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
      '2026-06-08',
      '2026-06-09',
      '2026-06-10',
      '2026-06-11',
      '2026-06-12',
      '2026-06-13',
    ],
  },
  {
    slug: 'the-amazing-digital-circus-the-last-act-2026',
    title: 'The Amazing Digital Circus: The Last Act',
    year: 2026,
    durationMin: 93,
    genres: [
      'Δραματική',
      'Κομεντί',
      'Μυστηρίου',
      'Περιπέτεια',
      'Τρόμου',
      'Ψυχολογικό Δράμα',
    ],
    director: 'Γκουσγουόρκς',
    cast: [],
    description: 'Η viral διαδικτυακή επιτυχία αίσθηση «The Amazing Digital Circus» φτάνει στο πολυαναμενόμενο τέλος της με μια μεγάλου μήκους κινηματογραφική κυκλοφορία!',
    poster: 'https://www.thessalonikiguide.gr/wp-content/uploads/2026/05/The-Amazing-Digital-Circus-The-Last-Act.jpg',
    url: 'https://www.thessalonikiguide.gr/tainia/the-amazing-digital-circus-the-last-act-2026/',
    cinemas: [
      'Odeon Πλατεία',
      'Options Μακεδονία (Πρώην Odeon)',
      'Cineplexx One Salonica',
      'Village Cosmos',
    ],
    screenings: [
      {
        cinema: 'Odeon Πλατεία',
        cinemaSlug: 'odeon-plateia',
        hall: 'Αίθουσα 2',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '19:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '19:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '19:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '19:00',
            ],
          },
        ],
      },
      {
        cinema: 'Options Μακεδονία (Πρώην Odeon)',
        cinemaSlug: 'odeon-makedonia',
        hall: 'Αίθουσα 4',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '19:20',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '19:20',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '19:20',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '19:20',
            ],
          },
        ],
      },
      {
        cinema: 'Cineplexx One Salonica',
        cinemaSlug: 'one-salonica',
        hall: 'Αίθουσα 7',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '18:00',
              '20:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '18:00',
              '20:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '18:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '18:00',
            ],
          },
        ],
      },
      {
        cinema: 'Village Cosmos',
        cinemaSlug: 'village-cosmos',
        hall: 'Αίθουσα 7',
        sessions: [
          {
            date: '2026-06-04',
            times: [
              '18:00',
              '20:00',
            ],
          },
          {
            date: '2026-06-05',
            times: [
              '17:30',
              '20:00',
            ],
          },
          {
            date: '2026-06-06',
            times: [
              '17:30',
              '20:00',
            ],
          },
          {
            date: '2026-06-07',
            times: [
              '17:30',
              '20:00',
            ],
          },
        ],
      },
    ],
    dates: [
      '2026-06-04',
      '2026-06-05',
      '2026-06-06',
      '2026-06-07',
    ],
  },
];
