import { IFilm } from '../../../interfaces/IFilm';

/**
 * AUTO-GENERATED by tools/scrape-cinema.mjs — do not edit by hand.
 * Sources: https://www.thessalonikiguide.gr/cinema/ (Θεσσαλονίκη), https://www.athinorama.gr/cinema (Αθήνα)
 * Generated: 2026-07-30T09:38:32.000Z
 *
 * Re-run `npm run scrape:cinema` to refresh the listings and showtimes.
 */
export const SCRAPED_AT = '2026-07-30T09:38:32.000Z';

export const FILMS: IFilm[] = [

];
