/** One day's showtimes for a film at a single cinema/hall. */
export interface IScreeningSession {
  /** ISO date, e.g. "2026-06-06". */
  date: string;
  /** Clock times that day, e.g. ["18:50", "21:30"]. */
  times: string[];
}

/** Everywhere/whenever a film plays at one cinema. */
export interface IScreening {
  cinema: string;
  cinemaSlug?: string;
  hall?: string;
  sessions: IScreeningSession[];
}

/**
 * A currently-playing film. Generated by tools/scrape-cinema.mjs from
 * thessalonikiguide.gr — see src/app/components/cinema/films.data.ts.
 */
export interface IFilm {
  slug: string;
  title: string;
  /** Original / international title, when different from the Greek one. */
  originalTitle?: string;
  year?: number;
  durationMin?: number;
  /** Genre tags (Greek), used for filtering. */
  genres: string[];
  /** IMDb rating out of 10, when available. */
  rating?: number;
  director?: string;
  cast?: string[];
  description?: string;
  /** Poster image URL. */
  poster?: string;
  /** Source page on thessalonikiguide.gr. */
  url: string;
  /** Distinct cinema names showing the film. */
  cinemas: string[];
  screenings: IScreening[];
  /** Distinct ISO dates the film screens on, sorted ascending. */
  dates: string[];
}
